import { ProductDataType } from "../type/productDataTypeDH";

export const PRODUCT_DATA2: Array<ProductDataType> = [
  {
    id: 1,
    name: "느린마을 막걸리킷(단품)",
    tags: {
      best: false,
      newProduct: false,
      recommend: true,
    },
    soldOut: true,
    like: false,
    sale: 30,
    price: "7,000",
    salePrice: "4,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1.jpg",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1_detail.jpg",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1_info.png",
    stock: 0,
    subscribe: false,
    twinkle: false,
  },
  {
    id: 2,
    name: "느린마을 막걸리 5입 + 나무잔",
    tags: {
      best: false,
      newProduct: true,
      recommend: true,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "23,900",
    salePrice: "23,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_2.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_2_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_2_info.png",
    stock: 396,
    subscribe: false,
    twinkle: false,
  },
  {
    id: 3,
    name: "느린마을 증류주 미니세트",
    tags: {
      best: false,
      newProduct: true,
      recommend: true,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "10,000",
    salePrice: "10,000",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_3.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_3_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_3_info.png",
    stock: 210,
    subscribe: false,
    twinkle: false,
  },
  {
    id: 4,
    name: "느린마을 나무잔",
    tags: {
      best: false,
      newProduct: true,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 15,
    price: "15,000",
    salePrice: "12,750",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_4.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_4_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_4_info.png",
    stock: 167,
    subscribe: false,
    twinkle: false,
  },
  {
    id: 5,
    name: "느린마을 막걸리 사계절 패키지",
    tags: {
      best: false,
      newProduct: true,
      recommend: true,
    },
    soldOut: false,
    like: true,
    sale: 0,
    price: "11,900",
    salePrice: "11,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_5.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_5_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_5_info.png",
    stock: 243,
    subscribe: false,
    twinkle: false,
  },
  {
    id: 6,
    name: "느린마을 막걸리킷(단품)",
    tags: {
      best: false,
      newProduct: false,
      recommend: true,
    },
    soldOut: true,
    like: false,
    sale: 30,
    price: "7,000",
    salePrice: "4,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1.jpg",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1_detail.jpg",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_1_info.png",
    stock: 0,
    subscribe: false,
    twinkle: true,
  },
  {
    id: 7,
    name: "느린마을X플랜40 스툴(블랙컬러)패키지",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: true,
    like: false,
    sale: 25,
    price: "27,900",
    salePrice: "20,925",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_7.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_7_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_7_info.png",
    stock: 0,
    subscribe: false,
    twinkle: true,
  },
  {
    id: 8,
    name: "심술7 버블 6입",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 10,
    price: "16,500",
    salePrice: "14,850",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_8.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_8_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_8_info.png",
    stock: 16,
    subscribe: false,
    twinkle: true,
  },
  {
    id: 9,
    name: "심술 6입",
    tags: {
      best: false,
      newProduct: false,
      recommend: true,
    },
    soldOut: false,
    like: false,
    sale: 10,
    price: "16,500",
    salePrice: "14,850",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_9.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_9_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_9_info.png",
    stock: 11,
    subscribe: false,
    twinkle: true,
  },
  {
    id: 10,
    name: "안동소주 일품 3입",
    tags: {
      best: true,
      newProduct: false,
      recommend: true,
    },
    soldOut: false,
    like: false,
    sale: 20,
    price: "19,900",
    salePrice: "15,920",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_10.jpeg",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_10_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_10_info.png",
    stock: 7,
    subscribe: false,
    twinkle: true,
  },
  {
    id: 11,
    name: "[구독] 느린마을 막걸리750 5입",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "14,900",
    salePrice: "14,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_11.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_11_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_11_info.png",
    stock: 122,
    subscribe: true,
    twinkle: false,
  },
  {
    id: 12,
    name: "[구독] 느린마을 소주21 3입",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "36,000",
    salePrice: "36,000",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_12.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_12_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_12_info.png",
    stock: 300,
    subscribe: true,
    twinkle: false,
  },
  {
    id: 13,
    name: "[구독] 느린마을 막걸리750 3입",
    tags: {
      best: true,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "9,500",
    salePrice: "9,500",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_13.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_13_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_13_info.png",
    stock: 401,
    subscribe: true,
    twinkle: false,
  },
  {
    id: 14,
    name: "[구독] 심술 5입",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "13,900",
    salePrice: "13,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_14.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_14_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_14_info.png",
    stock: 149,
    subscribe: true,
    twinkle: false,
  },
  {
    id: 15,
    name: "[구독] 느린마을 증류주 6입",
    tags: {
      best: false,
      newProduct: false,
      recommend: false,
    },
    soldOut: false,
    like: true,
    sale: 0,
    price: "17,900",
    salePrice: "17,900",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_15.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_15_detail.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_15_info.png",
    stock: 231,
    subscribe: true,
    twinkle: false,
  },
  {
    id: 16,
    name: "[팝업한정] 느린마을 연구소 세트 1호",
    tags: {
      best: false,
      newProduct: true,
      recommend: true,
    },
    soldOut: false,
    like: false,
    sale: 0,
    price: "25,000",
    salePrice: "25,000",
    image: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_16.png",
    detailImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_16.png",
    imageInfoImage: "https://homesool.s3.ap-northeast-2.amazonaws.com/alcohol_15_info.png",
    stock: 1,
    subscribe: false,
    twinkle: false,
  },
];
