export { ReactComponent as AlertIcon } from "./icon/alertCircleIc.svg";
export { ReactComponent as BackButtonIc } from "./icon/backButtonIc.svg";
export { ReactComponent as CheckIcon } from "./icon/checkIc.svg";
export { ReactComponent as CheckButton } from "./icon/checkRadioIc.svg";
export { ReactComponent as CloseDetailInfoIcon } from "./icon/closeIcon.svg";
export { ReactComponent as CommonFooterIc } from "./icon/commonFooterIc.svg";
export { ReactComponent as DetailProductIc } from "./icon/datailProductImg.svg";
export { ReactComponent as DetailAskRectangleIc } from "./icon/detailAskRectangleIc.svg";
export { ReactComponent as DetailEllipseIc } from "./icon/detailEllipseIc.svg";
export { ReactComponent as DetailFoldIc } from "./icon/detailFoldIc.svg";
export { ReactComponent as DetailNoReviewIc } from "./icon/detailNoReviewIc.svg";
export { ReactComponent as DetailSeeAllIc } from "./icon/detailSeeAllIc.svg";
export { ReactComponent as DetailUnfoldIc } from "./icon/detailUnfoldIc.svg";
export { ReactComponent as FooterHomeActiveIc } from "./icon/footerHomeActiveIc.svg";
export { ReactComponent as FooterHomeIc } from "./icon/footerHomeIc.svg";
export { ReactComponent as FooterIc } from "./icon/footerIc.svg";
export { ReactComponent as FooterMyActiveIc } from "./icon/footerMyActiveIc.svg";
export { ReactComponent as FooterMyIc } from "./icon/footerMyIc.svg";
export { ReactComponent as HomeHeaderIc } from "./icon/homeHeaderIc.svg";
export { ReactComponent as HomeIndicatorChromeIc } from "./icon/homeIndicatorChromeIc.svg";
export { ReactComponent as MainHomeSoolIc } from "./icon/homesool.svg";
export { ReactComponent as GrayLikeIc, ReactComponent as GrayLikeIcon } from "./icon/likeGray.svg";
export { ReactComponent as LikeIc } from "./icon/likeIc.svg";
export { ReactComponent as OrangeLikeIc, ReactComponent as OrangeLikeIcon } from "./icon/likeOrange.svg";
export { ReactComponent as MinusIc } from "./icon/minusIconIc.svg";
export { ReactComponent as MoveToSilverBannerIc } from "./icon/moveToSilverBannerIc.svg";
export { ReactComponent as MyPageUpdateProfileIc } from "./icon/myPageUpdateProfileIc.svg";
export { ReactComponent as MyPageUserProfileImgIc } from "./icon/myPageUserProfileImgIc.svg";
export { ReactComponent as NonCheckButton } from "./icon/nonCheckRadioIc.svg";
export { ReactComponent as NoneCheckIcon } from "./icon/noneCheckIc.svg";
export { ReactComponent as OpenDetailInfoIcon } from "./icon/openIcon.svg";
export { ReactComponent as OriginalHomeSoolIc } from "./icon/originalHomeSoolIc.svg";
export { ReactComponent as PagenationDotIc } from "./icon/pagenationDotIc.svg";
export { ReactComponent as PagenationSelectedDotIc } from "./icon/pagenationSelectedDotIc.svg";
export { ReactComponent as PlusIc } from "./icon/plusIconIc.svg";
export { ReactComponent as SeeAllIc } from "./icon/right.svg";
export { ReactComponent as ShareIc } from "./icon/shareIc.svg";
export { ReactComponent as RightSideOpenButton } from "./icon/sideOpenIcon.svg";
export { ReactComponent as SoldOutIc, ReactComponent as SoldOutIcon } from "./icon/sold_out.svg";
export { ReactComponent as OneStarIc, ReactComponent as OneStarIcon } from "./icon/star1.svg";
export { ReactComponent as TwoStarIc, ReactComponent as TwoStarIcon } from "./icon/star2.svg";
export { ReactComponent as ThreeStarIc, ReactComponent as ThreeStarIcon } from "./icon/star3.svg";
export { ReactComponent as FourStarIc, ReactComponent as FourStarIcon } from "./icon/star4.svg";
export { ReactComponent as FiveStarIc, ReactComponent as FiveStarIcon } from "./icon/star5.svg";
export { ReactComponent as BestTagIc, ReactComponent as BestTagIcon } from "./icon/tag_best.svg";
export { ReactComponent as NewTagIc, ReactComponent as NewTagIcon } from "./icon/tag_new.svg";
export { ReactComponent as RecommendTagIc, ReactComponent as RecommendTagIcon } from "./icon/tag_recommend.svg";
export { ReactComponent as SoldOutTagIc, ReactComponent as SoldOutTagIcon } from "./icon/tag_soldout.svg";
export { ReactComponent as TimeSaleIc } from "./icon/timesale.svg";
export { ReactComponent as TriangleOpenIcon } from "./icon/triangleOpenIc.svg";
